import { createFileRoute, Link } from "@tanstack/react-router";
import { Logo } from "@/components/Logo";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — TongueSync AI" },
      { name: "description", content: "The terms governing your use of TongueSync AI." },
      { property: "og:title", content: "Terms of Service — TongueSync AI" },
      { property: "og:description", content: "The terms governing your use of TongueSync AI." },
      { property: "og:url", content: "https://tonguesyncai.com/terms" },
    ],
    links: [{ rel: "canonical", href: "https://tonguesyncai.com/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-white">
      <header className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5">
        <Logo />
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-slate-300 hover:text-white transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back home
        </Link>
      </header>
      <article className="mx-auto max-w-3xl px-6 pb-24 pt-8">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight bg-gradient-to-r from-fuchsia-300 to-amber-200 bg-clip-text text-transparent">Terms of Service</h1>
        <p className="mt-4 text-sm text-slate-400">Last updated: July 2026</p>

        <section className="mt-10 space-y-6 text-slate-300 leading-relaxed">
          <div>
            <h2 className="text-xl font-semibold text-white">1. Acceptable use</h2>
            <p className="mt-2">You may only submit content you own or have rights to process. Illegal content, harassment, and impersonation are strictly prohibited.</p>
          </div>
          <div>
            <h2 className="text-xl font-semibold text-white">2. Ownership</h2>
            <p className="mt-2">You retain full ownership of your source videos and every clip, dub, and asset generated by TongueSync AI on your behalf.</p>
          </div>
          <div>
            <h2 className="text-xl font-semibold text-white">3. Subscription & billing</h2>
            <p className="mt-2">Pro plans renew monthly. You can cancel, upgrade, or downgrade at any time from the billing dashboard. Refunds are handled per our fair-use policy.</p>
          </div>
          <div>
            <h2 className="text-xl font-semibold text-white">4. Service availability</h2>
            <p className="mt-2">We work hard to keep the service fast and reliable but do not guarantee uninterrupted access. Scheduled maintenance windows are announced in advance.</p>
          </div>
          <div>
            <h2 className="text-xl font-semibold text-white">5. Liability</h2>
            <p className="mt-2">TongueSync AI is provided "as is." To the extent permitted by law, our liability is limited to the fees you paid in the 3 months preceding a claim.</p>
          </div>
        </section>
      </article>
    </div>
  );
}