/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TsSecretGate2026RouteImport } from './routes/ts-secret-gate-2026'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDubbingRouteImport } from './routes/_authenticated/dubbing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClipperRouteImport } from './routes/_authenticated/clipper'
import { Route as AuthenticatedActionVideoIdRouteImport } from './routes/_authenticated/action.$videoId'

const TsSecretGate2026Route = TsSecretGate2026RouteImport.update({
  id: '/ts-secret-gate-2026',
  path: '/ts-secret-gate-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDubbingRoute = AuthenticatedDubbingRouteImport.update({
  id: '/dubbing',
  path: '/dubbing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClipperRoute = AuthenticatedClipperRouteImport.update({
  id: '/clipper',
  path: '/clipper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActionVideoIdRoute =
  AuthenticatedActionVideoIdRouteImport.update({
    id: '/action/$videoId',
    path: '/action/$videoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/terms': typeof TermsRoute
  '/ts-secret-gate-2026': typeof TsSecretGate2026Route
  '/clipper': typeof AuthenticatedClipperRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dubbing': typeof AuthenticatedDubbingRoute
  '/action/$videoId': typeof AuthenticatedActionVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/terms': typeof TermsRoute
  '/ts-secret-gate-2026': typeof TsSecretGate2026Route
  '/clipper': typeof AuthenticatedClipperRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dubbing': typeof AuthenticatedDubbingRoute
  '/action/$videoId': typeof AuthenticatedActionVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/showcase': typeof ShowcaseRoute
  '/terms': typeof TermsRoute
  '/ts-secret-gate-2026': typeof TsSecretGate2026Route
  '/_authenticated/clipper': typeof AuthenticatedClipperRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dubbing': typeof AuthenticatedDubbingRoute
  '/_authenticated/action/$videoId': typeof AuthenticatedActionVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/showcase'
    | '/terms'
    | '/ts-secret-gate-2026'
    | '/clipper'
    | '/dashboard'
    | '/dubbing'
    | '/action/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/showcase'
    | '/terms'
    | '/ts-secret-gate-2026'
    | '/clipper'
    | '/dashboard'
    | '/dubbing'
    | '/action/$videoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/showcase'
    | '/terms'
    | '/ts-secret-gate-2026'
    | '/_authenticated/clipper'
    | '/_authenticated/dashboard'
    | '/_authenticated/dubbing'
    | '/_authenticated/action/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TermsRoute: typeof TermsRoute
  TsSecretGate2026Route: typeof TsSecretGate2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ts-secret-gate-2026': {
      id: '/ts-secret-gate-2026'
      path: '/ts-secret-gate-2026'
      fullPath: '/ts-secret-gate-2026'
      preLoaderRoute: typeof TsSecretGate2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dubbing': {
      id: '/_authenticated/dubbing'
      path: '/dubbing'
      fullPath: '/dubbing'
      preLoaderRoute: typeof AuthenticatedDubbingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clipper': {
      id: '/_authenticated/clipper'
      path: '/clipper'
      fullPath: '/clipper'
      preLoaderRoute: typeof AuthenticatedClipperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action/$videoId': {
      id: '/_authenticated/action/$videoId'
      path: '/action/$videoId'
      fullPath: '/action/$videoId'
      preLoaderRoute: typeof AuthenticatedActionVideoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClipperRoute: typeof AuthenticatedClipperRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDubbingRoute: typeof AuthenticatedDubbingRoute
  AuthenticatedActionVideoIdRoute: typeof AuthenticatedActionVideoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClipperRoute: AuthenticatedClipperRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDubbingRoute: AuthenticatedDubbingRoute,
  AuthenticatedActionVideoIdRoute: AuthenticatedActionVideoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ShowcaseRoute: ShowcaseRoute,
  TermsRoute: TermsRoute,
  TsSecretGate2026Route: TsSecretGate2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
